# Site settings
title: Michael Farias's Portfolio
description: MichaelFarias's personal portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://micael-farias.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Farias
user_description: Sou Michael Farias de Lima, um desenvolvedor de software versátil e experiente, com sólida formação em várias áreas da tecnologia. Minha expertise abrange desenvolvimento backend e frontend, com proficiência em linguagens como C#, Java e Ruby, além de frameworks como .NET, Rails e Spring Boot. Tenho participado de diversos projetos acadêmicos e profissionais, aplicando minhas habilidades em contextos práticos e desafiadores. Procuro sempre agregar valor onde eu pôr as mãos.
user_title: Estudante de Engenharia de Software
email: michaelfarias374@gmail.com
github_username:  micael-farias
twitter_username: _null
gplus_username:  _null

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
