# Site settings
title: Michael Farias's Portfolio
description: MichaelFarias's personal portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://micael-farias.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Farias
user_description: Eu sou Michael Farias de Lima, um desenvolvedor de software versátil e experiente, com uma sólida formação em várias áreas da tecnologia. Minha expertise abrange tanto o desenvolvimento backend quanto frontend, com proficiência em diversas linguagens de programação e frameworks modernos. Tenho uma paixão por C#, Java e Ruby, além de frameworks como .NET, Rails e Spring Boot. Ao longo da minha carreira, participei de diversos projetos acadêmicos e profissionais que me permitiram aplicar essas habilidades em contextos práticos e desafiadores. Isso inclui o desenvolvimento de sistemas web complexos, aplicativos móveis inovadores e soluções de software empresariais. Estou sempre em busca de novos desafios e oportunidades para aplicar e expandir meu conhecimento em desenvolvimento de software. Meu objetivo é continuar contribuindo para projetos inovadores e impactantes, aplicando as melhores práticas de engenharia de software e sempre agregar valor onde eu pôr as mãos.
user_title: Estudante de Engenharia de Software
email: michaelfarias374@gmail.com
github_username:  micael-farias
twitter_username: _null
gplus_username:  _null

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
